FROM ubuntu:22.04

RUN apt update && apt install -y autoconf automake autotools-dev curl python3 python3-pip libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev ninja-build git cmake libglib2.0-dev libslirp-dev unzip 


WORKDIR /root

RUN git clone --depth 1 https://github.com/riscv-collab/riscv-gnu-toolchain.git && \
    cd riscv-gnu-toolchain && \
    ./configure --prefix=/opt/toolchains/riscv32 --with-arch=rv32g --with-abi=ilp32d && \
    make && \
    rm -rf /root/riscv-gnu-toolchain
